Repository OliverHz28/PC3Proyecto10, pull requests merged in 2025-06, with the labels that each got.

#6 merge[#4]: feature/config-modifier a feature/develop
  .gitignore
  config.json
  main.py
  requirements.txt
  src/config_modifier.py
Labels: Important

#7 merge[#2]: feature/test a feature/develop
  .gitignore
  tests/test_config_modifier.py
Labels: Important, tests

#11 Feature/tests
  tests/test_config_modifier.py
Labels: bug

#23 chore[#22]: tag v1.0.0 y merge release branch a main
  .github/workflows/pr_validation.yaml
  .gitignore
  README.md
  config.json
  hooks/commit-msg
  hooks/pre-push
  pytest.ini
  requirements.txt
  scripts/lint_all.sh
  src/config_modifier.py
  tests/test_config_modifier.py
Labels: documentation, Important, sprint 1

#28 feat[#13]: merge feature/AUTO_INCR_VERSION a develop
  src/config_modifier.py
  tests/test_config_modifier.py
Labels: Important

#30 test[#29]: agregar pruebas unitarias para check_pr.py
  tests/test_check_pr.py
Labels: Important, tests

#36 test[#29]: agregar tests para check_pr.py
  scripts/check_pr.py
  tests/test_check_pr.py
Labels: tests

#37 feat[#19]: merge Feature/extender-workflow a develop
  .github/workflows/pr_validation.yaml
  bandit_report.txt
Labels: Important, sprint 2

#40 chore[#38]: tag v2.0.0 y merge release-sprint2 branch a main
  .github/workflows/pr_validation.yaml
  .gitignore
  CHANGELOG.md
  README.md
  pr_simulation/13/commits.txt
  pr_simulation/13/pr_13_title.txt
  pr_simulation/2/commits.txt
  pr_simulation/2/pr_2_title.txt
  pr_simulation/22/commits.txt
  pr_simulation/22/pr_22_title.txt
  pr_simulation/24/commits.txt
  pr_simulation/24/pr_24_title.txt
  pr_simulation/29/commits.txt
  pr_simulation/29/pr_29_title.txt
  requirements.txt
  scripts/check_pr.py
  scripts/lint_all.sh
  src/config_modifier.py
  src/logger.py
  tests/test_check_pr.py
  tests/test_config_modifier.py
  tests/test_logger.py
Labels: documentation, Important, sprint 2

#52 chore[#49]: tag v3.0.0 Sprint3
  .github/workflows/pr_validation.yaml
  .gitignore
  README.md
  scripts/check_pr.py
  scripts/lint_all.sh
  scripts/log_pr.py
  src/vulnerable.py
  tests/test_check_pr.py
  tests/test_log_pr.py
Labels: documentation, Sprint-3, Important
